spring:
  main:
    banner-mode: off
  application:
    name: exchange-rates-api
---
server:
  port: 8080
---
logging:
  level:
    com:
      gmail:
        arthurstrokov:
          exchangeratesapi:
            gateway:
              ExchangeRatesFeignClient: debug
---
feign:
  client:
    config:
      default:
        errorDecoder: com.gmail.arthurstrokov.exchangeratesapi.exceptions.RetreiveMessageErrorDecoder
        loggerLevel: basic
        connectTimeout: 1000
        readTimeout: 6000
