spring:
  main:
    banner-mode: off
  application:
    name: exchange-rates-api
---
server:
  port: 8080
---
logging:
  level:
    com:
      gmail:
        arthurstrokov:
          exchangeratesapi:
            gateway:
              ExchangeRatesFeignClient: debug
---
feign:
  client:
    config:
      default:
        loggerLevel: FULL
